# Generated by Django 4.1.4 on 2023-06-02 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URLS')),
            ],
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_one_day', models.IntegerField(null=True, verbose_name='Разовое')),
                ('price_ticket', models.IntegerField(null=True, verbose_name='Абонемент')),
                ('text_direction', models.CharField(max_length=10000, verbose_name='Описание')),
                ('location', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('name_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_test.category', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name_direction'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_school', models.CharField(default="Школа музыки и танца 'MAXIMUM skill' для детей от 3 до 16 лет. Мы находимся по адресам: - СК «Олимпийский» ул. Новая 17; - БЦ Премьер ул. Терешковой 263/2 Школа дополнительного образования «Максимум skill» для детей с 3-х лет, основана в 2018 году. Филиал №1 - имеет следующие направления деятельности: ТАНЦЫ для детей с 3-х лет. Современная хореография, Шаффл, Брейк-данс, растяжка, отличная физ. подготовка. МОДЕЛЬНОЕ МАСТЕРСТВО. Подиум, фотопозирование, фотосьемка. АКТЕРСКОЕ МАСТЕРСТВО. Театр, постановка мюзикла. Филиал №2 – имеет следующие направления деятельности: ЭСТРАДНЫЙ ВОКАЛ, ИГРА НА ГИТАРЕ, МАСТЕР КЛАССЫ ТВОРЧЕСКИЕ ДЛЯ ДЕТЕЙ. МИССИЯ ШКОЛЫ – дать детям все самое ценное, а именно skill – навык, умение, мастерство, искусство, здоровье и развитие личности! Дети получают полноценные занятия, теоретические и практические. В программе обучения: развитие музыкального слуха, развитие чувства ритма, постановка голоса, постановка номеров, запись песен на профессиональной студии звукозаписи. Выступают коллективом на международных конкурсах, городских площадках, а также на отчетных концертах школы.", max_length=100000, verbose_name='О Нас')),
                ('count_teacher', models.IntegerField(verbose_name='Количество учителей')),
                ('count_pupil', models.IntegerField(verbose_name='Количество учеников')),
                ('count_directions', models.IntegerField(default='5', verbose_name='Количество направлений')),
            ],
            options={
                'verbose_name': 'О Школе',
                'verbose_name_plural': 'О Школе',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_presentation', models.CharField(max_length=100, verbose_name='Выступления')),
                ('text', models.CharField(max_length=10000, verbose_name='Описание')),
                ('link', models.URLField(max_length=100, verbose_name='Ссылка')),
                ('photo', models.ImageField(upload_to='app_test/photo/', verbose_name='Фото')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата мероприятия')),
                ('direction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_test.directions')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=1000)),
                ('your_phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('select_direction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_test.directions')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['id'],
            },
        ),
    ]
